### ISSUE TITLE
RxODE and Berkeley Madonna gave different simulation results 

### ISSUE THREAD

**Issue by UNCcrawler** [hallowkm/RxODE#15]
Hi, has anyone noticed that RxODE and Berkeley gave different simulation results? Apparently, they use different stiff ode solvers. RxODE uses LSODA, and Berkeley uses Rosenbrock. I also noticed that the time step for RxODE is fixed to integer? I don't know the root reason and would like to know if this is specific to my case. Thanks.

**Comment by Sibojang9** [comment]
That is really a good question but I haven't found any noticeable difference.

**Comment by mattfidler** [comment]
In theory, all ode solvers will give the correct solution, but in practice that may not be true, especially in stiff systems.  LSODA allows switching between stiff and non-stiff. 

I'm not sure what you mean by "the time step is fixed to an integer".  Could you please explain?

Also the development of RxODE has moved to:

https://github.com/nlmixrdevelopment/RxODE

**Comment by UNCcrawler** [comment]
Thank you for the comments. I am a new user of R. I soon realized that the time step was set by me to be integers in $add.sampling and also realized that $add.sampling was the output time, not the actual time step in the solver. But I still have the simulation problem. I have a complex model, which has several stiff functions. I found the reason for RxODE gave different simulation results is that few variables were not changed and remained as the initial values. I couldn't figure out the reason why these variables were not changed. I greatly appreciate any suggestions. The ode equations were copied from Berkeley code, so the equations should be correct. I am using RxODE because it is easier to code complex dosing regimens and it can be coupled with ggplot. Thank you for developing such a great simulation tool.

**Comment by UNCcrawler** [comment]
Update: The initial values I mentioned above is 0. RxODE was running properly, but the returned results were small and therefore 0. I think the problem that RxODE and Berkerley gave different results is due to the ODE solver. I have multiple stiff equations. I will try to use calcJac=TRUE.

**Comment by wwang-at-github** [comment]
no, that can't be the case. the default option with rxode is stiff=T, hence
using lsoda to solve the system.

i think you have other errors in your code.

**Comment by UNCcrawler** [comment]
Hi, thanks for your reply. I did set stiff = T. The equations were copied
from Berkeley code. Except the settings for initials, I didn't find any
difference. The dosing regimen is IV bolus, so I set initial in Berkeley as
dose/volume and in RxODE as 0. The drug I am trying to simulate shows
dose-dependent clearance. RxODE simulation results had no such traits,  so
I feel something is wrong with my RxODE simulation. I haven't tried calcJac
= TRUE due to a installation problem with SnakecharmR.

Which part of the code would you suggest me to double-check?  Any
suggestions would be greatly appreciated.

**Comment by wwang-at-github** [comment]
share your code then

**Comment by UNCcrawler** [comment]
If possible, can I share the code with you in private?

**Comment by wwang-at-github** [comment]
sure. wwang8198@gmail.com
